- name: Play for Registers
  hosts: all
  tasks:
    - name: Execute Shell
      shell: uptime
      register: OUT
    - name: Printing the OUTPUT
      debug:
        msg: "{{OUT.stdout}}"
    - name: Setting the status
      set_fact:
        STATUS: "{{OUT.rc}}"
    - name: Printing the status
      debug:
        msg: the status is {{STATUS}}
