- name: Demoplay
  hosts: all
  become: yes
  tasks:
      - name: Demo on adding block 
        blockinfile:
          path: /home/ec2-user/demo.cpy
          create: yes 
          block: |
            Match User ansible-agent
            PasswordAuthentication no
