- name: Copying the tempolate with passing the argument
  hosts: all
  become: yes
  tasks:
    - name: for getting the templates
      template:
        src: template.conf
        dest: /home/ec2-user/template.conf