- name: Play-1 for vars
  hosts: all
  vars:
    URL: www.google.com
  vars_file:
    - proj-a.yaml
  tasks:
    - name: Printing the URL
      debug:
        msg: "{{URL}}"
    - name: Printing the URL from Local variable
      debug:
        msg: "{{URL}}"
      vars:
        URL: www.URL.com
    - name: Printing URL from the CLI
      debug:
        msg: The CLI var is {{URL_FROM_CLI}}
    - name: Printing from file a
      debug:
        msg: The var from file is {{FILE_URL}}