- name: Play-1
  hosts: all
  vars:
    URL: www.google.com
  tasks:
    - name: Printing the URL
      debug:
        msg: "{{URL}}"
    - name: Printing the URL
      debug:
        msg: "{{URL}}"
      vars:
        URL: www.URL.com