- name: for webapp 
  hosts: all
  become: yes
  tasks:
    - name: installing HTTPD
      package:
        name: httpd
        state: present

    - name: copying the proxy.conf
      copy:  
        src: proxy.conf
        dest: /etc/httpd/conf.d/proxy.conf 

