- name: Installing java
  package:
    name: java

- name: Adding the student user
  user:
    name: "{{APPUSER}}"
    comment: Application user

- name: Downloading the tomacat App
  unarchive:
    src: "{{TOMCAT_URL}}" 
    dest: "{{APPUSERHOME}}"
    remote_src: yes

