- name: Installing java
  package:
    name: java

- name: Adding the student user
  user:
    name: "{{APPUSER}}"
    comment: Application user

- name: Downloading the tomacat App
  unarchive:
    src: "{{TOMCAT_URL}}" 
    dest: "{{APPUSERHOME}}"
    remote_src: yes
  become_user: "{{APPUSER}}"

- name: Downloading the war file
  get_url:
    url: "{{WAR_URL}}"
    dest: "{{APPUSER}}/apache-tomcat-{{TOMCAT_VERSION}}/webapps/"
  become_user: "{{APPUSER}}"

- name: Dowloading the jar file
  get_url:
    url: "{{JAR_URL}}"
    dest: "{{APPUSER}}/apache-tomcat-{{TOMCAT_VERSION}}/lib/"
  become_user: "{{APPUSER}}"


