- name: Installing java
  package:
    name: java

- name: Adding the student user
  user:
    name: "{{APPUSER}}"
    comment: Application user

- name: Downloading the tomacat App
  unarchive:
    src: "{{TOMCAT_URL}}" 
    dest: "{{APPUSERHOME}}"
    remote_src: yes
  become_user: "{{APPUSER}}"

- name: Downloading the war file
  get_url:
    url: "{{WAR_URL}}"
    dest: "{{APPUSERHOME}}/apache-tomcat-{{TOMCAT_VERSION}}/webapps/"
    mode: '0775'
  become_user: "{{APPUSER}}"

- name: Dowloading the jar file
  get_url:
    url: "{{JAR_URL}}"
    dest: "{{APPUSERHOME}}/apache-tomcat-{{TOMCAT_VERSION}}/lib/"
    mode: '0775'
  become_user: "{{APPUSER}}"

- name: Copying the context.xml file
  template:
    src: context.xml
    dest: "{{APPUSERHOME}}/apache-tomcat-{{TOMCAT_VERSION}}/conf/"
    mode: '0775'
  become_user: "{{APPUSER}}"

- name: Copying the systemd file 
  copy:  
    src: student.service
    dest: /etc/systemd/system/multi-user.target.wants/
    mode: '0775'
- name: Starting the startup
  shell: "{{APPUSERHOME}}/apache-tomcat-{{TOMCAT_VERSION}}/bin/startup.sh"




